### ISSUE TITLE
Uncompleted\unpolished features.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11386]
**(please not manage this issue, i use it to control over my list.)**

- [ ] **1) Transport**
- [ ] - 1) **Steam tractor** QoL modules in storage - https://github.com/StrangeLoopGames/EcoIssues/issues/10009
- [ ] - 2) **Steam tractor** No module shortcut\help (like excavator\skidsteer) on toolbar - https://github.com/StrangeLoopGames/EcoIssues/issues/8101
- [ ] - 3) **Steam tractor** No way to swith sower\harvester state (but plough have it... it's strange for me) - https://github.com/StrangeLoopGames/EcoIssues/issues/8103
- [ ] - 4) **Steam tractor** Modules in tractor is not protected from steal - https://github.com/StrangeLoopGames/EcoIssues/issues/8705
- [ ] - 5)  (failed, closed w\o fix) **Steam tractor** Tractor can plow other users land w\o authorization - https://github.com/StrangeLoopGames/EcoIssues/issues/10130
- [ ] - 6) Auto move - https://github.com/StrangeLoopGames/EcoSuggestions/issues/702
- [ ] - 7) Engine on\off - https://github.com/StrangeLoopGames/EcoSuggestions/issues/703
- [ ] - 8) Light on\off - https://github.com/StrangeLoopGames/EcoSuggestions/issues/704
- [ ] - 9) Horn - https://github.com/StrangeLoopGames/EcoSuggestions/issues/203, https://github.com/StrangeLoopGames/EcoSuggestions/issues/677
- [ ] - 10) More auth parameters - https://github.com/StrangeLoopGames/EcoSuggestions/issues/706
- [ ] - 11) Powered Cart return - https://github.com/StrangeLoopGames/EcoIssues/issues/11291

- [ ] **2) Sleep**
- [ ] - 1) If someone pickup bed - you have problem. https://github.com/StrangeLoopGames/EcoIssues/issues/10637
- [ ] - 2) Sleep in campsite bed - https://github.com/StrangeLoopGames/EcoIssues/issues/10057
- [ ] - 3) Bed sleeping animation missing (for other players) - https://github.com/StrangeLoopGames/EcoIssues/issues/9996

- [ ] **3) Ladders**
- [x] - 1) Missing flat steel (art ready) - https://github.com/StrangeLoopGames/EcoIssues/issues/10123
- [ ] - 2) objects ladders missed - https://github.com/StrangeLoopGames/EcoIssues/issues/10002
- [ ] - 3) no "exit on top" - https://github.com/StrangeLoopGames/EcoIssues/issues/9908

- [ ] **4) Ramps**
- [ ] - 1) Produce road x2 less cost (ramps) - https://github.com/StrangeLoopGames/EcoIssues/issues/9667
- [ ] - 2) No connection to closest blocks - https://github.com/StrangeLoopGames/EcoIssues/issues/9668
- [ ] - 3) Huge difference vs puckup and place - https://github.com/StrangeLoopGames/EcoIssues/issues/9301
- [ ] - 4) Ramp part names in road info - https://github.com/StrangeLoopGames/EcoIssues/issues/9320
- [x] - 5) Different speed bonus - https://github.com/StrangeLoopGames/EcoIssues/issues/11337
- [ ] - 6) No occupancy check while placing - https://github.com/StrangeLoopGames/EcoIssues/issues/10554
- [ ] - 7) law interactions - https://github.com/StrangeLoopGames/EcoIssues/issues/9891, https://github.com/StrangeLoopGames/EcoIssues/issues/10066
- [ ] - 8) Ramps can be picked-up by showel - https://github.com/StrangeLoopGames/EcoIssues/issues/11384

- [ ] **6) Smog**
- [ ] - 1) Some objects have pipe connector but not produce smog - https://github.com/StrangeLoopGames/EcoIssues/issues/8507
- [ ] - 2) Water and smog layers - https://github.com/StrangeLoopGames/EcoIssues/issues/9775

- [ ] **7) Collisions**
- [ ] - 1) Carved Pumpkin - https://github.com/StrangeLoopGames/EcoIssues/issues/11185
- [ ] - 2) Bank - https://github.com/StrangeLoopGames/EcoIssues/issues/11081
- [ ] - 3) Treasury - https://github.com/StrangeLoopGames/EcoIssues/issues/10576
- [ ] - 4) Oil refinery - https://github.com/StrangeLoopGames/EcoIssues/issues/10401
- [ ] - 5) Stuffed ELK - https://github.com/StrangeLoopGames/EcoIssues/issues/10910
- [ ] - 6) Robotic Assembly Line - https://github.com/StrangeLoopGames/EcoIssues/issues/8099
- [ ] - 7) Wind Turbines - https://github.com/StrangeLoopGames/EcoIssues/issues/5464, https://github.com/StrangeLoopGames/EcoIssues/issues/9530

- [ ] **8) Animations**

- [ ] **9) Seat**
- [ ] - 1) Couch - https://github.com/StrangeLoopGames/EcoIssues/issues/10120
- [ ] - 2) Issues - https://github.com/StrangeLoopGames/EcoIssues/issues/10073, https://github.com/StrangeLoopGames/EcoIssues/issues/11382

- [ ] **10) Pipes**
- [ ] - 1) Multiple content at same time - https://github.com/StrangeLoopGames/EcoIssues/issues/10214
- [ ] - 2) Leak - https://github.com/StrangeLoopGames/EcoIssues/issues/11363
- [ ] - 3) (failed) Pipes connection to the water - https://github.com/StrangeLoopGames/EcoIssues/issues/10221

- [ ] **11) Power**
- [ ] - 1) Steam engine provide electrical - https://github.com/StrangeLoopGames/EcoIssues/issues/8652
- [ ] - 2) Combustion generator require water and looks as steam turbine - https://github.com/StrangeLoopGames/EcoIssues/issues/11212 
- [ ] - 3) Steam engine is not require water - https://github.com/StrangeLoopGames/EcoIssues/issues/11385
- [ ] - 4) Combustion generator uses coal - https://github.com/StrangeLoopGames/EcoIssues/issues/11085
- [ ] - 5) Incorrect actions - https://github.com/StrangeLoopGames/EcoIssues/issues/7240

- [ ] - **12) Sewage**
- [ ] - 1) disabled (by network) combustion generator provide sewage - https://github.com/StrangeLoopGames/EcoIssues/issues/11213
- [ ] - 2) Blast Furnace with idle job emits sewage - https://github.com/StrangeLoopGames/EcoIssues/issues/11268
- [ ] - 3) Too many compost from sewage - https://github.com/StrangeLoopGames/EcoIssues/issues/11217
- [x] - 4) Filter need hoverable "compost" in info - https://github.com/StrangeLoopGames/EcoIssues/issues/10340

- [ ] **13) Crane**
- [ ] - 1) Hook with no interface - https://github.com/StrangeLoopGames/EcoIssues/issues/8080
- [ ] - 2) Position resets - https://github.com/StrangeLoopGames/EcoIssues/issues/8085
- [ ] - 3) Angles - https://github.com/StrangeLoopGames/EcoIssues/issues/7911
- [ ] - 4) Usability - https://github.com/StrangeLoopGames/EcoIssues/issues/11411

**Comment by elfl0rd** [comment]
Closing, i'll no more free volunteer after direct lie from @D3nnis3n
