### ISSUE TITLE
Law UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13345]
**Recommended reading for this task:**
How the UI system works: https://github.com/StrangeLoopGames/Eco/wiki/UI-System
How game actions work: https://github.com/StrangeLoopGames/Eco/wiki/Game-Actions
How icons work: https://sites.google.com/strangeloopgames.com/team/tools/icons

**Tasks**
- [ ] Work with Milenko to implement an updated version of this UI.
![image](https://user-images.githubusercontent.com/3536496/66857131-7bc30c80-ef3b-11e9-9ffc-72b8b0d7efe9.png)
When doing so, give the margins a cleanup too. You can see the icons are hugging the edges here: 
![image](https://user-images.githubusercontent.com/3536496/66857844-f4769880-ef3c-11e9-9800-7de96d4692a3.png)

- [ ] Replace the garbage icon with the red-minus in all cases

- [ ] Need icons for all these types to display in the drop down. IE, they need to show their MarkedUpName in the dropdown, like when theyre displayed in a selector here: 
![image](https://user-images.githubusercontent.com/3536496/66857182-90070980-ef3b-11e9-96e2-d071408224a8.png)
![image](https://user-images.githubusercontent.com/3536496/66857249-b6c54000-ef3b-11e9-809c-8ec6037beb28.png)
Some dont have icons, like SetTimer.  Give Rob the list of icons needed and add them in once created.  Some icons are probably already there but just need their file renamed to match the name of the class.

- [ ] Make dropdown behave better. Make it position better in cases like this, and show more of the list (theres more veritcal space than is utilized).  'Better' is subjective so use your judgement to determine what would be the best option in cases like this. Perhaps we make it popup something in the middle of the screen instead, even. Discuss thoughts with johnk.  
![anim](https://user-images.githubusercontent.com/3536496/66857683-a3ff3b00-ef3c-11e9-8d95-cc38b60cdc77.gif)

**Comment by beastyn** [comment]
trash to minus is here #14954

Categories UI we can push for hotfixes, I think
