### ISSUE TITLE
Pool System Refactoring

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#16814]
We need to ensure pooling system is safe and easy to use. It will continue refactoring started by @serpopov in https://github.com/StrangeLoopGames/Eco/pull/6097

## Task list (behind already implemented):

- [x] Split IPoolableComponent onto IPoolRentAware and IPoolReturnAware. In most cases we only need IPoolReturnAware.
- [x] Add Development Mode client side chat command which will analyze all pool objects, compare instances with prefabs and report any difference to file. It should greatly simplify pooling issues troubleshooting.
   - [x] add client-side command /detectpoolissues
   - [x] add check for children game object hierarchy mismatches
   - [x] add check for component types (for every game object in hierarchy) mismatches
   - [x] add way to avoid false-positive mismatches (i.e. when some child objects or components may be created on demand and doesn't corrupt pooled instance state)
   - [x] add support for component-level pool mismatch resolving (avoiding false positives)
   - [x] add component vs component mismatches detection
   - [x] add mismatch resolver for standard unity classes (i.e. Image)
   - [x] add mismatch resolver for TMPro
   - [x] add mismatch member resolver for collections and arrays
- [x] Add [SupportsPooling] attribute which may be used for components which doesn't implement any of IPool*Aware interface.
- [x] For ObjectPool check if prefab and all it's children SupportsPooling and log warning if check failed.
- [x] When pooled object returned call pool callbacks on it's hierarchy, not only own components.
- [x] Update all components used with pool to implement either pooling interfaces or attribute them with [SupportsPooling].
