### ISSUE TITLE
Audio feedback 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16832]
- [x] 'Tick' sound when clicking UI is a bit prominent/tinny. In general would like to smooth out the percussive element of a lot of the UI sounds, make them more relaxing, something youd head in an ASMR video.  In general I'd like to have the soundscape for the UI be pretty subtle and relaxing, a lot of the UI sounds had an 'edge' to them we should soften up.

![image](https://user-images.githubusercontent.com/3536496/85343380-932aa000-b4a1-11ea-9a48-57cd5b5dd649.png)
- [x] Add a very unobtusive notice sound to popups.  Should be different for 'status' vs 'error'. Note that these appear all the time so it shouldnt sound too 'error-like'

- [x] Opening UIs via shortcut keys should make noise

![image](https://user-images.githubusercontent.com/3536496/85343581-10561500-b4a2-11ea-93b6-bfb3446e9f75.png)
- [x] Ocean sound was quite loud here, seemed like a bug

- [x] Walking on hard surfaces was a bit loud, footstep sound had two percussive elements too it, could make it less prominent with just one.

![image](https://user-images.githubusercontent.com/3536496/85343737-7a6eba00-b4a2-11ea-8fb8-3c382418cf26.png)
- [x] Striking scythe on this gave a very loud clang

![image](https://user-images.githubusercontent.com/3536496/85343770-94a89800-b4a2-11ea-8cc5-7b0513b033f9.png)
- [x] Need soft sound when tooltips appear

![animx22](https://user-images.githubusercontent.com/3536496/85343838-dc2f2400-b4a2-11ea-938a-6f08fc156716.gif)
- [x] When mousing over UI elements, many will highlight with your cursor appearing over them. This should be accompanied by a sound, and it should vary for different types of buttons.  It should be super subtle and soft.

![image](https://user-images.githubusercontent.com/3536496/85344124-9e7ecb00-b4a3-11ea-8eb0-84f326a7fd9d.png)
- [x] Checkbox didnt have sound
- [x] Other sounds in this dialog needed to be softer

![image](https://user-images.githubusercontent.com/3536496/85344216-e0a80c80-b4a3-11ea-822c-5730467470b7.png)
- [x] Falling log made a crackling sound

![image](https://user-images.githubusercontent.com/3536496/85344230-eaca0b00-b4a3-11ea-8b9d-93cf816a0bac.png)
- [x] No sound on pickup of these 

![animx22](https://user-images.githubusercontent.com/3536496/85344317-34b2f100-b4a4-11ea-8854-387566f9b9d5.gif)
- [x] Need cool sound for these scrolling effects, with different ones for large/medium/small

![image](https://user-images.githubusercontent.com/3536496/85344364-5613dd00-b4a4-11ea-93b9-542f360303a2.png)
- [x] Heard a raging ocean at this placid lake. Make the ocean detection only detect sea level water. Something very wrong with the ocean sound, its everywhere and overpowering.

![image](https://user-images.githubusercontent.com/3536496/85344418-78a5f600-b4a4-11ea-9cb5-072a014f848d.png)
- [x] Heard no water sounds at this river and waterfall

- [x] Heard one music track then no more after that.  Is it working? Are new tracks in? 

![image](https://user-images.githubusercontent.com/3536496/85792718-cf9c0d00-b6e8-11ea-9bea-10a305e45b9a.png)
- [x] Clicks not working on these left right buttons. Try all buttons in this dialog and title screen make sure they make noise, even after leaving and returning to screens.
