### ISSUE TITLE
Beta Staging 1742 Bug List on ECO Friendly gaming 9.0 server

### ISSUE THREAD

**Issue by Rjritchie** [StrangeLoopGames/EcoIssues#17981]
Stone Roads, Dirt Ramps- Cart Sound Stuck on road even when no cart on road.
Animals freezing: Error catch message displaying in background 
Arrastra Upgrade Module not registering 
No sound when cutting trees 
Water Wheel works even when not in water
Camas only yield 3 at full mature with gather level 6
Alligator came back after being killed off
Small rug goes under Mortar Sandstone roof when placed on roof
Tier 1  salad food gives more Cals then Tier 2 salad? Maybe not bug? 

If we find more we'll post

**Comment by Rjritchie** [comment]
When I ate Fern Campfire Salad, I saw The Developer Error Catch Code Appear. I had also gotten it the first time I put down the Cast Iron Stove

**Comment by Rjritchie** [comment]
![ERROR CODE](https://user-images.githubusercontent.com/62763005/91650679-979aa880-ea50-11ea-9c00-fcb15d221bd1.png)

**Comment by IcedForge** [comment]
The Arrastra module not registering, are you refering to the resources not being reduced? That would be intended  (mouse over description details it is STATIC value meaning it wont change which is also indicated by a yellow border around the resource cost)

Or are you having issues with no time reduction?

**Comment by Rjritchie** [comment]
I talked to the guy that was reporting the error, you are correct, he misread the description and thought it was like the other modules. The Arrastra modules works correctly.

**Comment by SlayksWood** [comment]
@Rjritchie Thank you for the report.
I will separate you issue to different points. and closed this issue.

- [ ] Stone Roads, Dirt Ramps- Cart Sound Stuck on road even when no cart on road. - #17772

- [ ] Animals freezing: Error catch message displaying in background - we have a lot of issues, it's not full complete yet.

- [ ] Arrastra Upgrade Module not registering - not a issue.

- [ ] No sound when cutting trees - will investigate it. I can't reproduce it, but some players sometimes have this issue too.

- [ ] Water Wheel works even when not in water - #2105

- [ ] Camas only yield 3 at full mature with gather level 6. - It depends on many factors, so If you have any problem open separate issue with more details. This system works not ideal for now. Maybe your feedback could help us.

- [ ] Alligator came back after being killed off - #18000, this issue after staging-1746

- [ ] Small rug goes under Mortar Sandstone roof when placed on roof - create a separate issue #18009

- [ ] Tier 1 salad food gives more Cals then Tier 2 salad? Maybe not bug? - It can give more calories, but it should give less nutrients: Tier 1 - 28; Tier 2 - 38.
