### ISSUE TITLE
Declunkify: 3rd person camera

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#22102]
- [x] Make the default more zoomed in
- [x] Something is wrong with zooming in, its really slow and doesnt get very close.  It also slows down when youre reaching the extents, it should not do this, it should be a constant scroll regardless of how close it is to the avatar. Make it zoom quite far, above their head so its not blocking the view. It should zoom like 3x faster than it does now. Make it awesome.  
- [x] Make the game start in 3rd person camera by default
- [x] When moving a direction youre not facing, make the avatar turn in place a lot faster (reference other games)
- [x] Make the third person camera tighter. After you stop moving, it lerps a bit still (see https://user-images.githubusercontent.com/3536496/120907739-c87bbf80-c618-11eb-838e-70d5a97302cc.gif)
Make it instant like the first person camera.
